apiVersion: v1
kind: Service
metadata:
  name: ticket-booking-service
spec:
  selector:
    app: ticket-booking-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 8020
      targetPort: 8020
      nodePort: 30007
